# Generated by Django 5.2.4 on 2025-07-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('availability', models.IntegerField(default=0)),
            ],
        ),
    ]
