# Generated by Django 5.2.4 on 2025-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fruitsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitsVendors',
            fields=[
                ('vendor_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=60)),
                ('vendor_location', models.CharField(max_length=60)),
            ],
        ),
    ]
